from typing import Generic, TypeVar

from sqlalchemy import Select
from sqlalchemy.ext.asyncio import AsyncSession

ModelType = TypeVar("ModelType")


class BaseRepository(Generic[ModelType]):
    """
    Generic repository containing common database operations.

    NOTE:
    Repositories NEVER commit transactions.
    Services control commit/rollback.
    """

    def __init__(
        self,
        db: AsyncSession,
    ):
        self.db = db

    # ======================================================
    # Create
    # ======================================================

    async def create(
        self,
        obj: ModelType,
    ) -> ModelType:

        self.db.add(obj)

        # Push INSERT to DB without committing
        await self.db.flush()

        # Populate autogenerated fields (UUID/defaults)
        await self.db.refresh(obj)

        return obj

    # ======================================================
    # Update
    # ======================================================

    async def update(self):

        await self.db.flush()

    # ======================================================
    # Delete
    # ======================================================

    async def delete(
        self,
        obj: ModelType,
    ):

        await self.db.delete(obj)

        await self.db.flush()

    # ======================================================
    # Refresh
    # ======================================================

    async def refresh(
        self,
        obj: ModelType,
    ):

        await self.db.refresh(obj)

    # ======================================================
    # Execute
    # ======================================================

    async def execute(
        self,
        stmt: Select,
    ):

        return await self.db.execute(stmt)

    # ======================================================
    # Transaction
    # ======================================================

    async def flush(self):

        await self.db.flush()

    async def commit(self):

        await self.db.commit()

    async def rollback(self):

        await self.db.rollback()
