"""add attachment encryption

Revision ID: 5aad8dd25c18
Revises: 4babf4cb83b2
Create Date: 2026-07-29 16:26:28.472501

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5aad8dd25c18"
down_revision: str | Sequence[str] | None = "4babf4cb83b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade():

    # Existing attachments are NOT encrypted
    op.add_column(
        "attachments",
        sa.Column(
            "encrypted",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "attachments",
        sa.Column(
            "encrypted_key_sender",
            sa.Text(),
            nullable=True,
        ),
    )

    op.add_column(
        "attachments",
        sa.Column(
            "encrypted_key_receiver",
            sa.Text(),
            nullable=True,
        ),
    )

    op.add_column(
        "attachments",
        sa.Column(
            "nonce",
            sa.Text(),
            nullable=True,
        ),
    )

    # remove default for future inserts
    op.alter_column(
        "attachments",
        "encrypted",
        server_default=None,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("attachments", "message_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("attachments", "nonce")
    op.drop_column("attachments", "encrypted_key_receiver")
    op.drop_column("attachments", "encrypted_key_sender")
    op.drop_column("attachments", "encrypted")
    # ### end Alembic commands ###
